### ISSUE TITLE
install requirements.txt  and runing script

### ISSUE THREAD

**Issue by logan71f100** [ArthurMoore85/pi_romulus#18]
im on the latest version of retropi and after running the requirements script this is outputted 
---------------------------------------------------------------
pi@retropie:~/pi_romulus $ pip install -r requirements.txt
Downloading/unpacking beautifulsoup4==4.5.1 (from -r requirements.txt (line 1))
  Downloading beautifulsoup4-4.5.1-py2-none-any.whl (83kB): 83kB downloaded
Downloading/unpacking bs4==0.0.1 (from -r requirements.txt (line 2))
  Downloading bs4-0.0.1.tar.gz
  Running setup.py (path:/tmp/pip-build-cX8xoj/bs4/setup.py) egg_info for package bs4
    
Downloading/unpacking EasyProcess==0.2.3 (from -r requirements.txt (line 3))
  Downloading EasyProcess-0.2.3.tar.gz
  Running setup.py (path:/tmp/pip-build-cX8xoj/EasyProcess/setup.py) egg_info for package EasyProcess
    
    warning: no files found matching 'TODO*'
    warning: no files found matching 'CHANGES*'
    no previously-included directories found matching 'docs/_build'
Downloading/unpacking libarchive==0.4.3 (from -r requirements.txt (line 4))
  Downloading libarchive-0.4.3-py2-none-any.whl
Downloading/unpacking mechanize==0.2.5 (from -r requirements.txt (line 5))
  Downloading mechanize-0.2.5.tar.gz (383kB): 383kB downloaded
  Running setup.py (path:/tmp/pip-build-cX8xoj/mechanize/setup.py) egg_info for package mechanize
    
Downloading/unpacking nose==1.3.7 (from -r requirements.txt (line 6))
  Downloading nose-1.3.7-py2-none-any.whl (154kB): 154kB downloaded
Requirement already satisfied (use --upgrade to upgrade): npyscreen==4.10.5 in /usr/local/lib/python2.7/dist-packages/npyscreen-4.10.5-py2.7.egg (from -r requirements.txt (line 7))
Downloading/unpacking pyunpack==0.1.2 (from -r requirements.txt (line 8))
  Downloading pyunpack-0.1.2.tar.gz
  Running setup.py (path:/tmp/pip-build-cX8xoj/pyunpack/setup.py) egg_info for package pyunpack
    
    warning: no files found matching 'TODO*'
    warning: no files found matching 'CHANGES*'
    no previously-included directories found matching 'docs/_build'
Downloading/unpacking requests==2.12.4 (from -r requirements.txt (line 9))
  Downloading requests-2.12.4-py2.py3-none-any.whl (576kB): 576kB downloaded
Installing collected packages: beautifulsoup4, bs4, EasyProcess, libarchive, mechanize, nose, pyunpack, requests
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 295, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 672, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 902, in move_wheel_files
    pycompile=self.pycompile,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 214, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 204, in clobber
    os.makedirs(destdir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/bs4'

Storing debug log for failure in /home/pi/.pip/pip.log
pi@retropie:~/pi_romulus $ 
----------------------------------------------------------------------------------------------------
after that when i try to run the script i get 

------------------------------------------------------------------------------------------------
pi@retropie:~/pi_romulus $ sudo python romulus.py
Traceback (most recent call last):
  File "romulus.py", line 9, in <module>
    from forms import SearchForm
  File "/home/pi/pi_romulus/forms/__init__.py", line 8, in <module>
    from forms.search import SearchForm
  File "/home/pi/pi_romulus/forms/search.py", line 12, in <module>
    from api.providers import EmuApi
  File "/home/pi/pi_romulus/api/providers/__init__.py", line 12, in <module>
    from .emuapi import EmuApi
  File "/home/pi/pi_romulus/api/providers/emuapi.py", line 17, in <module>
    from api.base import Api
  File "/home/pi/pi_romulus/api/base.py", line 16, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named bs4
pi@retropie:~/pi_romulus $ 
--------------------------------------------------------------------------------------------------

**Comment by logan71f100** [comment]
attached is the debug output for second half of the problem

[pip.log](https://github.com/ArthurMoore85/pi_romulus/files/1576616/pip.log)

**Comment by logan71f100** [comment]
first issue can be fixed by putting sudo in front of pip install -r requirements.txt, could you make a bullet-ed list for install like

- git clone https://github.com/ArthurMoore85/pi_romulus
- cd pi_romulus
- sudo apt-get install python-pip libarchive-dev
- sudo pip install -r requirements.txt
- python romulus.py

**Comment by ArthurMoore85** [comment]
Thank you for your feedback and taking the time to go through those steps.

Did your steps fix all the problems and it runs again?

I'll absolutely take your recommendation and update the installation guide when I get home.

**Comment by logan71f100** [comment]
yup, its working now, really happy i found this thank you! if you get around to adding that progress bar then this is complete. im going to look under the hood a bit and see how you parse the site, see if i could add another

**Comment by ArthurMoore85** [comment]
I have had an initial look into the progressbar, but it's not part of the widget set for the UI library I use, but will look into it in more detail.

I had also initially looked at other sites but the ones I looked at, all used JavaScript for download triggers which can be a pain to do using Python libraries. But I have begun the initial stages of using classes that are more abstract to allow support for other sites hopefully.

**Comment by logan71f100** [comment]
sounds like you have this all under control! i dont have much education in python, im all java but not script. i look forward to your progress on this, really making my living room a nicer place to game!
