### ISSUE TITLE
Adding other systems

### ISSUE THREAD

**Issue by romxuk** [ArthurMoore85/pi_romulus#19]
I just got this to try it out, It works well but does not work with all systems on the RPI. I tried with Nintendo DS and it downloaded them into the pi_romulus folder, so I went into directory_utils.py and added it there but this did not make it move the downloaded NDS games into the nds folder. I also added it into /home/pi/pi_romulus/api/resultitem.py

**Comment by ArthurMoore85** [comment]
Thank you for submitting the feature request.
The feature request has been added as a task on GitLab. You can keep a track of the progress here: https://gitlab.com/arthurmoore85/pi_romulus/issues/23

**Comment by ArthurMoore85** [comment]
@romxuk ,

My apologies for taking so long.
Nintendo DS has been added
