### ISSUE TITLE
Emuparaise rars some files

### ISSUE THREAD

**Issue by romxuk** [ArthurMoore85/pi_romulus#20]
Another issue I noticed, emuparadise compresses some games into rar like psx the downloaded rar goes into the roms folder but not roms/psx and not unpacked

**Comment by ArthurMoore85** [comment]
Thank you for your bug report.
Having investigated this, there is indeed an issue. I am currently working on a fix to push out, but please note that the games are being decompressed, but to the incorrect directory. I would recommend looking in the Pi Romulus install directory (where romulus.py is located) as you may find the games being located there.

**Comment by ArthurMoore85** [comment]
The bug has been fixed and hotfix has been applied into master branch. If you do a 'git pull' in the directory of pi_romulus, you should have no futher issues with this.
