### ISSUE TITLE
SCUMMVM

### ISSUE THREAD

**Issue by pietrondo** [ArthurMoore85/pi_romulus#28]
Hi!
Is possible in the next versions have the possibility to download SCUMMVM games?
thx

**Comment by ArthurMoore85** [comment]
Hello,
Thanks for the recommendation.
I will add it to the list for the next update.

**Comment by ArthurMoore85** [comment]
@pietrondo 

I have added SCUMMVM support. 
Please note that SCUMMVM is somewhat of an oddball on RetroPie. File formats are very different, and EmuParadise doesnt filter for that. Therefore please raise any issues that you encounter with it.
