### ISSUE TITLE
download stop working since few days (without any error message)

### ISSUE THREAD

**Issue by faf95** [ArthurMoore85/pi_romulus#33]
Hi,

Since few days, i notice pi_romulus download stop working.
I was using, and it working very fine before !

python program run correctly, showing search results roms as usualy.
After selecting rom, download windows appear, and back to main menu after 10 seconds.
I try with some roms, and result is same.

What log files should i check and report content here ?

Sorry for my english ;-)
Regards

**Comment by faf95** [comment]
pi_romulus 1.2.4
retropie 4.4.2
System: Linux 4.14.52-v7+ #1123 SMP Wed Jun 27 17:35:49 BST 2018 armv7l GNU/Linux

**Comment by faf95** [comment]
maybe related 

http://www.gamerevolution.com/news/416105-emuparadise-rom-downloads-no-longer-available-legal-trouble

**Comment by ArthurMoore85** [comment]
Thank you very much for reporting this.
The related article appears to be related. EmuParadise is the website used to download roms and with that feature gone, Romulus can no longer provide roms. I will look at other websites to see if this can be fixed.

**Comment by ArthurMoore85** [comment]
Update:
I can confirm that since EmuParadise have stopped hosting ROMs, this app currently no longer functions.
I am currently working on connecting the app to RomsMania.
The API however was created with EmuParadise in mind, and requires some substancial work in order to get it to function correctly using RomsMania. 

Note that the development has not halted, I am actively working on a fix.

**Comment by acujl** [comment]
what is status?

**Comment by EpicLPer** [comment]
> Note that the development has not halted, I am actively working on a fix.

I doubt that right now lol

**Comment by sasdallas** [comment]
3 years ago

**Comment by ArthurMoore85** [comment]
Sorry for the delay (3 years is an insane delay, and my sincere apologies, life got ahead of me).
However, I have now changed the source where we used to get ROMs (EmuParadise) as they no longer provide these, to RomDownload. Therefore if you pull the latest changes, could you confirm that you can now download as before?
